url: https://rokaso.com
name: Osvaldas Rokas blog
title: ""
description: ""
meta_description: ""
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
url_assets: 'https://d1ra7kav7kguzj.cloudfront.net'
baseurl: ''
google_analytics: 'UA-28179723-1'
#disqus: 'demowebsite'
include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-responsive-image
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Paginatio 
paginate: 21
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

responsive_image:
  template: _includes/responsive-image.html
  base_path: "_fullsize-images"
  output_path_format: _generated-smaller-size-images/%{width}/%{basename}
  sizes:
    - width: 480  # [Required] How wide the resized image will be.
      quality: 80 # [Optional] Overrides default_quality for this size.
    - width: 800
    - width: 1400
      quality: 90

